// <auto-generated/>

namespace SharpWintab.Wintab
{
    /// <summary>
    /// Functions
    /// </summary>
    public static partial class Functions
    {
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>unsigned int WTInfoA([In] unsigned int arg0,[In] unsigned int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTInfoA</unmanaged-short>
        public static unsafe System.UInt32 WTInfoA(System.UInt32 arg0, System.UInt32 arg1, System.IntPtr arg2)
        {
            System.UInt32 __result__;
            __result__ = WTInfoA_(arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTInfoA", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern System.UInt32 WTInfoA_(System.UInt32 param0, System.UInt32 param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>unsigned int WTInfoW([In] unsigned int arg0,[In] unsigned int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTInfoW</unmanaged-short>
        public static unsafe System.UInt32 WTInfoW(System.UInt32 arg0, System.UInt32 arg1, System.IntPtr arg2)
        {
            System.UInt32 __result__;
            __result__ = WTInfoW_(arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTInfoW", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern System.UInt32 WTInfoW_(System.UInt32 param0, System.UInt32 param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HCTX__* WTOpenA([In] HWND arg0,[In] LOGCONTEXTA* arg1,[In] BOOL arg2)</unmanaged>
        /// <unmanaged-short>WTOpenA</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hctx WTOpenA(System.Int32 arg0, ref SharpWintab.Wintab.Logcontexta arg1, SharpGen.Runtime.Win32.RawBool arg2)
        {
            SharpWintab.Wintab.Logcontexta.__Native arg1_ = default (SharpWintab.Wintab.Logcontexta.__Native);
            SharpWintab.Wintab.Hctx __result__;
            arg1.__MarshalTo(ref arg1_);
            __result__ = WTOpenA_(arg0, &arg1_, arg2);
            arg1.__MarshalFree(ref arg1_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTOpenA", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hctx WTOpenA_(int param0, void *param1, SharpGen.Runtime.Win32.RawBool param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HCTX__* WTOpenW([In] HWND arg0,[In] LOGCONTEXTW* arg1,[In] BOOL arg2)</unmanaged>
        /// <unmanaged-short>WTOpenW</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hctx WTOpenW(System.Int32 arg0, ref SharpWintab.Wintab.Logcontextw arg1, SharpGen.Runtime.Win32.RawBool arg2)
        {
            SharpWintab.Wintab.Logcontextw.__Native arg1_ = default (SharpWintab.Wintab.Logcontextw.__Native);
            SharpWintab.Wintab.Hctx __result__;
            arg1.__MarshalTo(ref arg1_);
            __result__ = WTOpenW_(arg0, &arg1_, arg2);
            arg1.__MarshalFree(ref arg1_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTOpenW", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hctx WTOpenW_(int param0, void *param1, SharpGen.Runtime.Win32.RawBool param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTClose([In] HCTX__* arg0)</unmanaged>
        /// <unmanaged-short>WTClose</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTClose(SharpWintab.Wintab.Hctx arg0)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTClose_(&arg0);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTClose", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTClose_(void *param0);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>int WTPacketsGet([In] HCTX__* arg0,[In] int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTPacketsGet</unmanaged-short>
        public static unsafe System.Int32 WTPacketsGet(SharpWintab.Wintab.Hctx arg0, System.Int32 arg1, System.IntPtr arg2)
        {
            System.Int32 __result__;
            __result__ = WTPacketsGet_(&arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTPacketsGet", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern int WTPacketsGet_(void *param0, int param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTPacket([In] HCTX__* arg0,[In] unsigned int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTPacket</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTPacket(SharpWintab.Wintab.Hctx arg0, System.UInt32 arg1, System.IntPtr arg2)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTPacket_(&arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTPacket", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTPacket_(void *param0, System.UInt32 param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTEnable([In] HCTX__* arg0,[In] BOOL arg1)</unmanaged>
        /// <unmanaged-short>WTEnable</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTEnable(SharpWintab.Wintab.Hctx arg0, SharpGen.Runtime.Win32.RawBool arg1)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTEnable_(&arg0, arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTEnable", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTEnable_(void *param0, SharpGen.Runtime.Win32.RawBool param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTOverlap([In] HCTX__* arg0,[In] BOOL arg1)</unmanaged>
        /// <unmanaged-short>WTOverlap</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTOverlap(SharpWintab.Wintab.Hctx arg0, SharpGen.Runtime.Win32.RawBool arg1)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTOverlap_(&arg0, arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTOverlap", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTOverlap_(void *param0, SharpGen.Runtime.Win32.RawBool param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTConfig([In] HCTX__* arg0,[In] HWND arg1)</unmanaged>
        /// <unmanaged-short>WTConfig</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTConfig(SharpWintab.Wintab.Hctx arg0, System.Int32 arg1)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTConfig_(&arg0, arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTConfig", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTConfig_(void *param0, int param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTGetA([In] HCTX__* arg0,[In] LOGCONTEXTA* arg1)</unmanaged>
        /// <unmanaged-short>WTGetA</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTGetA(SharpWintab.Wintab.Hctx arg0, ref SharpWintab.Wintab.Logcontexta arg1)
        {
            SharpWintab.Wintab.Logcontexta.__Native arg1_ = default (SharpWintab.Wintab.Logcontexta.__Native);
            SharpGen.Runtime.Win32.RawBool __result__;
            arg1.__MarshalTo(ref arg1_);
            __result__ = WTGetA_(&arg0, &arg1_);
            arg1.__MarshalFree(ref arg1_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTGetA", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTGetA_(void *param0, void *param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTGetW([In] HCTX__* arg0,[In] LOGCONTEXTW* arg1)</unmanaged>
        /// <unmanaged-short>WTGetW</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTGetW(SharpWintab.Wintab.Hctx arg0, ref SharpWintab.Wintab.Logcontextw arg1)
        {
            SharpWintab.Wintab.Logcontextw.__Native arg1_ = default (SharpWintab.Wintab.Logcontextw.__Native);
            SharpGen.Runtime.Win32.RawBool __result__;
            arg1.__MarshalTo(ref arg1_);
            __result__ = WTGetW_(&arg0, &arg1_);
            arg1.__MarshalFree(ref arg1_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTGetW", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTGetW_(void *param0, void *param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTSetA([In] HCTX__* arg0,[In] LOGCONTEXTA* arg1)</unmanaged>
        /// <unmanaged-short>WTSetA</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTSetA(SharpWintab.Wintab.Hctx arg0, ref SharpWintab.Wintab.Logcontexta arg1)
        {
            SharpWintab.Wintab.Logcontexta.__Native arg1_ = default (SharpWintab.Wintab.Logcontexta.__Native);
            SharpGen.Runtime.Win32.RawBool __result__;
            arg1.__MarshalTo(ref arg1_);
            __result__ = WTSetA_(&arg0, &arg1_);
            arg1.__MarshalFree(ref arg1_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTSetA", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTSetA_(void *param0, void *param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTSetW([In] HCTX__* arg0,[In] LOGCONTEXTW* arg1)</unmanaged>
        /// <unmanaged-short>WTSetW</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTSetW(SharpWintab.Wintab.Hctx arg0, ref SharpWintab.Wintab.Logcontextw arg1)
        {
            SharpWintab.Wintab.Logcontextw.__Native arg1_ = default (SharpWintab.Wintab.Logcontextw.__Native);
            SharpGen.Runtime.Win32.RawBool __result__;
            arg1.__MarshalTo(ref arg1_);
            __result__ = WTSetW_(&arg0, &arg1_);
            arg1.__MarshalFree(ref arg1_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTSetW", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTSetW_(void *param0, void *param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTExtGet([In] HCTX__* arg0,[In] unsigned int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTExtGet</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTExtGet(SharpWintab.Wintab.Hctx arg0, System.UInt32 arg1, System.IntPtr arg2)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTExtGet_(&arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTExtGet", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTExtGet_(void *param0, System.UInt32 param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTExtSet([In] HCTX__* arg0,[In] unsigned int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTExtSet</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTExtSet(SharpWintab.Wintab.Hctx arg0, System.UInt32 arg1, System.IntPtr arg2)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTExtSet_(&arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTExtSet", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTExtSet_(void *param0, System.UInt32 param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTSave([In] HCTX__* arg0,[In] void* arg1)</unmanaged>
        /// <unmanaged-short>WTSave</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTSave(SharpWintab.Wintab.Hctx arg0, System.IntPtr arg1)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTSave_(&arg0, (void *)arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTSave", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTSave_(void *param0, void *param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HCTX__* WTRestore([In] HWND arg0,[In] void* arg1,[In] BOOL arg2)</unmanaged>
        /// <unmanaged-short>WTRestore</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hctx WTRestore(System.Int32 arg0, System.IntPtr arg1, SharpGen.Runtime.Win32.RawBool arg2)
        {
            SharpWintab.Wintab.Hctx __result__;
            __result__ = WTRestore_(arg0, (void *)arg1, arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTRestore", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hctx WTRestore_(int param0, void *param1, SharpGen.Runtime.Win32.RawBool param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>int WTPacketsPeek([In] HCTX__* arg0,[In] int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTPacketsPeek</unmanaged-short>
        public static unsafe System.Int32 WTPacketsPeek(SharpWintab.Wintab.Hctx arg0, System.Int32 arg1, System.IntPtr arg2)
        {
            System.Int32 __result__;
            __result__ = WTPacketsPeek_(&arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTPacketsPeek", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern int WTPacketsPeek_(void *param0, int param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <param name = "arg4">No documentation.</param>
        /// <param name = "arg5">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>int WTDataGet([In] HCTX__* arg0,[In] unsigned int arg1,[In] unsigned int arg2,[In] int arg3,[In] void* arg4,[In] int* arg5)</unmanaged>
        /// <unmanaged-short>WTDataGet</unmanaged-short>
        public static unsafe System.Int32 WTDataGet(SharpWintab.Wintab.Hctx arg0, System.UInt32 arg1, System.UInt32 arg2, System.Int32 arg3, System.IntPtr arg4, System.Int32 arg5)
        {
            System.Int32 __result__;
            __result__ = WTDataGet_(&arg0, arg1, arg2, arg3, (void *)arg4, &arg5);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTDataGet", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern int WTDataGet_(void *param0, System.UInt32 param1, System.UInt32 param2, int param3, void *param4, void *param5);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <param name = "arg4">No documentation.</param>
        /// <param name = "arg5">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>int WTDataPeek([In] HCTX__* arg0,[In] unsigned int arg1,[In] unsigned int arg2,[In] int arg3,[In] void* arg4,[In] int* arg5)</unmanaged>
        /// <unmanaged-short>WTDataPeek</unmanaged-short>
        public static unsafe System.Int32 WTDataPeek(SharpWintab.Wintab.Hctx arg0, System.UInt32 arg1, System.UInt32 arg2, System.Int32 arg3, System.IntPtr arg4, System.Int32 arg5)
        {
            System.Int32 __result__;
            __result__ = WTDataPeek_(&arg0, arg1, arg2, arg3, (void *)arg4, &arg5);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTDataPeek", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern int WTDataPeek_(void *param0, System.UInt32 param1, System.UInt32 param2, int param3, void *param4, void *param5);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>int WTQueueSizeGet([In] HCTX__* arg0)</unmanaged>
        /// <unmanaged-short>WTQueueSizeGet</unmanaged-short>
        public static unsafe System.Int32 WTQueueSizeGet(SharpWintab.Wintab.Hctx arg0)
        {
            System.Int32 __result__;
            __result__ = WTQueueSizeGet_(&arg0);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTQueueSizeGet", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern int WTQueueSizeGet_(void *param0);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTQueueSizeSet([In] HCTX__* arg0,[In] int arg1)</unmanaged>
        /// <unmanaged-short>WTQueueSizeSet</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTQueueSizeSet(SharpWintab.Wintab.Hctx arg0, System.Int32 arg1)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTQueueSizeSet_(&arg0, arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTQueueSizeSet", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTQueueSizeSet_(void *param0, int param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HMGR__* WTMgrOpen([In] HWND arg0,[In] unsigned int arg1)</unmanaged>
        /// <unmanaged-short>WTMgrOpen</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hmgr WTMgrOpen(System.Int32 arg0, System.UInt32 arg1)
        {
            SharpWintab.Wintab.Hmgr __result__;
            __result__ = WTMgrOpen_(arg0, arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrOpen", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hmgr WTMgrOpen_(int param0, System.UInt32 param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrClose([In] HMGR__* arg0)</unmanaged>
        /// <unmanaged-short>WTMgrClose</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrClose(SharpWintab.Wintab.Hmgr arg0)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrClose_(&arg0);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrClose", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrClose_(void *param0);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrContextEnum([In] HMGR__* arg0,[In] __function__stdcall* arg1,[In] LONG_PTR arg2)</unmanaged>
        /// <unmanaged-short>WTMgrContextEnum</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrContextEnum(SharpWintab.Wintab.Hmgr arg0, SharpGen.Runtime.FunctionCallback arg1, System.IntPtr arg2)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrContextEnum_(&arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrContextEnum", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrContextEnum_(void *param0, void *param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HWND WTMgrContextOwner([In] HMGR__* arg0,[In] HCTX__* arg1)</unmanaged>
        /// <unmanaged-short>WTMgrContextOwner</unmanaged-short>
        public static unsafe System.Int32 WTMgrContextOwner(SharpWintab.Wintab.Hmgr arg0, SharpWintab.Wintab.Hctx arg1)
        {
            System.Int32 __result__;
            __result__ = WTMgrContextOwner_(&arg0, &arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrContextOwner", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern int WTMgrContextOwner_(void *param0, void *param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HCTX__* WTMgrDefContext([In] HMGR__* arg0,[In] BOOL arg1)</unmanaged>
        /// <unmanaged-short>WTMgrDefContext</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hctx WTMgrDefContext(SharpWintab.Wintab.Hmgr arg0, SharpGen.Runtime.Win32.RawBool arg1)
        {
            SharpWintab.Wintab.Hctx __result__;
            __result__ = WTMgrDefContext_(&arg0, arg1);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrDefContext", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hctx WTMgrDefContext_(void *param0, SharpGen.Runtime.Win32.RawBool param1);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HCTX__* WTMgrDefContextEx([In] HMGR__* arg0,[In] unsigned int arg1,[In] BOOL arg2)</unmanaged>
        /// <unmanaged-short>WTMgrDefContextEx</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hctx WTMgrDefContextEx(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, SharpGen.Runtime.Win32.RawBool arg2)
        {
            SharpWintab.Wintab.Hctx __result__;
            __result__ = WTMgrDefContextEx_(&arg0, arg1, arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrDefContextEx", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hctx WTMgrDefContextEx_(void *param0, System.UInt32 param1, SharpGen.Runtime.Win32.RawBool param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>unsigned int WTMgrDeviceConfig([In] HMGR__* arg0,[In] unsigned int arg1,[In] HWND arg2)</unmanaged>
        /// <unmanaged-short>WTMgrDeviceConfig</unmanaged-short>
        public static unsafe System.UInt32 WTMgrDeviceConfig(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, System.Int32 arg2)
        {
            System.UInt32 __result__;
            __result__ = WTMgrDeviceConfig_(&arg0, arg1, arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrDeviceConfig", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern System.UInt32 WTMgrDeviceConfig_(void *param0, System.UInt32 param1, int param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrExt([In] HMGR__* arg0,[In] unsigned int arg1,[In] void* arg2)</unmanaged>
        /// <unmanaged-short>WTMgrExt</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrExt(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, System.IntPtr arg2)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrExt_(&arg0, arg1, (void *)arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrExt", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrExt_(void *param0, System.UInt32 param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrCsrEnable([In] HMGR__* arg0,[In] unsigned int arg1,[In] BOOL arg2)</unmanaged>
        /// <unmanaged-short>WTMgrCsrEnable</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrCsrEnable(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, SharpGen.Runtime.Win32.RawBool arg2)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrCsrEnable_(&arg0, arg1, arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrCsrEnable", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrCsrEnable_(void *param0, System.UInt32 param1, SharpGen.Runtime.Win32.RawBool param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrCsrButtonMap([In] HMGR__* arg0,[In] unsigned int arg1,[In] unsigned char* arg2,[In] unsigned char* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrCsrButtonMap</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrCsrButtonMap(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, System.Byte arg2, System.Byte arg3)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrCsrButtonMap_(&arg0, arg1, &arg2, &arg3);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrCsrButtonMap", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrCsrButtonMap_(void *param0, System.UInt32 param1, void *param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrCsrPressureBtnMarks([In] HMGR__* arg0,[In] unsigned int arg1,[In] DWORD arg2,[In] DWORD arg3)</unmanaged>
        /// <unmanaged-short>WTMgrCsrPressureBtnMarks</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrCsrPressureBtnMarks(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, System.Int32 arg2, System.Int32 arg3)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrCsrPressureBtnMarks_(&arg0, arg1, arg2, arg3);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrCsrPressureBtnMarks", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrCsrPressureBtnMarks_(void *param0, System.UInt32 param1, int param2, int param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrCsrPressureResponse([In] HMGR__* arg0,[In] unsigned int arg1,[In] unsigned int* arg2,[In] unsigned int* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrCsrPressureResponse</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrCsrPressureResponse(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, System.UInt32 arg2, System.UInt32 arg3)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrCsrPressureResponse_(&arg0, arg1, &arg2, &arg3);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrCsrPressureResponse", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrCsrPressureResponse_(void *param0, System.UInt32 param1, void *param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrCsrExt([In] HMGR__* arg0,[In] unsigned int arg1,[In] unsigned int arg2,[In] void* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrCsrExt</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrCsrExt(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, System.UInt32 arg2, System.IntPtr arg3)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrCsrExt_(&arg0, arg1, arg2, (void *)arg3);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrCsrExt", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrCsrExt_(void *param0, System.UInt32 param1, System.UInt32 param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTQueuePacketsEx([In] HCTX__* arg0,[In] unsigned int* arg1,[In] unsigned int* arg2)</unmanaged>
        /// <unmanaged-short>WTQueuePacketsEx</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTQueuePacketsEx(SharpWintab.Wintab.Hctx arg0, System.UInt32 arg1, System.UInt32 arg2)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTQueuePacketsEx_(&arg0, &arg1, &arg2);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTQueuePacketsEx", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTQueuePacketsEx_(void *param0, void *param1, void *param2);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrConfigReplaceExA([In] HMGR__* arg0,[In] BOOL arg1,[In] char* arg2,[In] char* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrConfigReplaceExA</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrConfigReplaceExA(SharpWintab.Wintab.Hmgr arg0, SharpGen.Runtime.Win32.RawBool arg1, System.String arg2, System.String arg3)
        {
            System.IntPtr arg2_;
            System.IntPtr arg3_;
            SharpGen.Runtime.Win32.RawBool __result__;
            arg2_ = System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(arg2);
            arg3_ = System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(arg3);
            __result__ = WTMgrConfigReplaceExA_(&arg0, arg1, (void *)arg2_, (void *)arg3_);
            System.Runtime.InteropServices.Marshal.FreeHGlobal(arg2_);
            System.Runtime.InteropServices.Marshal.FreeHGlobal(arg3_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrConfigReplaceExA", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrConfigReplaceExA_(void *param0, SharpGen.Runtime.Win32.RawBool param1, void *param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrConfigReplaceExW([In] HMGR__* arg0,[In] BOOL arg1,[In] wchar_t* arg2,[In] char* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrConfigReplaceExW</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrConfigReplaceExW(SharpWintab.Wintab.Hmgr arg0, SharpGen.Runtime.Win32.RawBool arg1, System.String arg2, System.String arg3)
        {
            System.IntPtr arg3_;
            SharpGen.Runtime.Win32.RawBool __result__;
            arg3_ = System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(arg3);
            fixed (char *arg2_ = arg2)
                __result__ = WTMgrConfigReplaceExW_(&arg0, arg1, (void *)arg2_, (void *)arg3_);
            System.Runtime.InteropServices.Marshal.FreeHGlobal(arg3_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrConfigReplaceExW", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrConfigReplaceExW_(void *param0, SharpGen.Runtime.Win32.RawBool param1, void *param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HWTHOOK__* WTMgrPacketHookExA([In] HMGR__* arg0,[In] int arg1,[In] char* arg2,[In] char* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrPacketHookExA</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hwthook WTMgrPacketHookExA(SharpWintab.Wintab.Hmgr arg0, System.Int32 arg1, System.String arg2, System.String arg3)
        {
            System.IntPtr arg2_;
            System.IntPtr arg3_;
            SharpWintab.Wintab.Hwthook __result__;
            arg2_ = System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(arg2);
            arg3_ = System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(arg3);
            __result__ = WTMgrPacketHookExA_(&arg0, arg1, (void *)arg2_, (void *)arg3_);
            System.Runtime.InteropServices.Marshal.FreeHGlobal(arg2_);
            System.Runtime.InteropServices.Marshal.FreeHGlobal(arg3_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrPacketHookExA", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hwthook WTMgrPacketHookExA_(void *param0, int param1, void *param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>HWTHOOK__* WTMgrPacketHookExW([In] HMGR__* arg0,[In] int arg1,[In] wchar_t* arg2,[In] char* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrPacketHookExW</unmanaged-short>
        public static unsafe SharpWintab.Wintab.Hwthook WTMgrPacketHookExW(SharpWintab.Wintab.Hmgr arg0, System.Int32 arg1, System.String arg2, System.String arg3)
        {
            System.IntPtr arg3_;
            SharpWintab.Wintab.Hwthook __result__;
            arg3_ = System.Runtime.InteropServices.Marshal.StringToHGlobalAnsi(arg3);
            fixed (char *arg2_ = arg2)
                __result__ = WTMgrPacketHookExW_(&arg0, arg1, (void *)arg2_, (void *)arg3_);
            System.Runtime.InteropServices.Marshal.FreeHGlobal(arg3_);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrPacketHookExW", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpWintab.Wintab.Hwthook WTMgrPacketHookExW_(void *param0, int param1, void *param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrPacketUnhook([In] HWTHOOK__* arg0)</unmanaged>
        /// <unmanaged-short>WTMgrPacketUnhook</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrPacketUnhook(SharpWintab.Wintab.Hwthook arg0)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrPacketUnhook_(&arg0);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrPacketUnhook", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrPacketUnhook_(void *param0);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>LONG_PTR WTMgrPacketHookNext([In] HWTHOOK__* arg0,[In] int arg1,[In] UINT_PTR arg2,[In] LONG_PTR arg3)</unmanaged>
        /// <unmanaged-short>WTMgrPacketHookNext</unmanaged-short>
        public static unsafe System.IntPtr WTMgrPacketHookNext(SharpWintab.Wintab.Hwthook arg0, System.Int32 arg1, System.UIntPtr arg2, System.IntPtr arg3)
        {
            System.IntPtr __result__;
            __result__ = WTMgrPacketHookNext_(&arg0, arg1, arg2, (void *)arg3);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrPacketHookNext", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern System.IntPtr WTMgrPacketHookNext_(void *param0, int param1, System.UIntPtr param2, void *param3);
        /// <summary>
        /// No documentation.
        /// </summary>
        /// <param name = "arg0">No documentation.</param>
        /// <param name = "arg1">No documentation.</param>
        /// <param name = "arg2">No documentation.</param>
        /// <param name = "arg3">No documentation.</param>
        /// <returns>No documentation.</returns>
        /// <unmanaged>BOOL WTMgrCsrPressureBtnMarksEx([In] HMGR__* arg0,[In] unsigned int arg1,[In] unsigned int* arg2,[In] unsigned int* arg3)</unmanaged>
        /// <unmanaged-short>WTMgrCsrPressureBtnMarksEx</unmanaged-short>
        public static unsafe SharpGen.Runtime.Win32.RawBool WTMgrCsrPressureBtnMarksEx(SharpWintab.Wintab.Hmgr arg0, System.UInt32 arg1, System.UInt32 arg2, System.UInt32 arg3)
        {
            SharpGen.Runtime.Win32.RawBool __result__;
            __result__ = WTMgrCsrPressureBtnMarksEx_(&arg0, arg1, &arg2, &arg3);
            return __result__;
        }

        [System.Runtime.InteropServices.DllImportAttribute("Wintab32.dll", EntryPoint = "WTMgrCsrPressureBtnMarksEx", CallingConvention = System.Runtime.InteropServices.CallingConvention.StdCall)]
        private unsafe static extern SharpGen.Runtime.Win32.RawBool WTMgrCsrPressureBtnMarksEx_(void *param0, System.UInt32 param1, void *param2, void *param3);
    }
}