// <auto-generated/>

namespace SharpWintab
{
    internal static partial class LocalInterop
    {
        public static unsafe System.UInt32 CalliStdCallFuncSystemUInt32(System.UInt32 param0, System.UInt32 param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpWintab.Wintab.Hctx CalliStdCallFuncSharpWintabWintabHctx0(int param0, void *param1, SharpGen.Runtime.Win32.RawBool param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallFuncint(void *param0, int param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, System.UInt32 param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool0(void *param0, SharpGen.Runtime.Win32.RawBool param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, int param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallFuncint(void *param0, System.UInt32 param1, System.UInt32 param2, int param3, void *param4, void *param5, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallFuncint(void *param0, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpWintab.Wintab.Hmgr CalliStdCallFuncSharpWintabWintabHmgr(int param0, System.UInt32 param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, void *param1, void *param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe int CalliStdCallFuncint(void *param0, void *param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpWintab.Wintab.Hctx CalliStdCallFuncSharpWintabWintabHctx0(void *param0, SharpGen.Runtime.Win32.RawBool param1, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpWintab.Wintab.Hctx CalliStdCallFuncSharpWintabWintabHctx0(void *param0, System.UInt32 param1, SharpGen.Runtime.Win32.RawBool param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.UInt32 CalliStdCallFuncSystemUInt32(void *param0, System.UInt32 param1, int param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool0(void *param0, System.UInt32 param1, SharpGen.Runtime.Win32.RawBool param2, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, System.UInt32 param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, System.UInt32 param1, int param2, int param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool(void *param0, System.UInt32 param1, System.UInt32 param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpGen.Runtime.Win32.RawBool CalliStdCallFuncSharpGenRuntimeWin32RawBool0(void *param0, SharpGen.Runtime.Win32.RawBool param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe SharpWintab.Wintab.Hwthook CalliStdCallFuncSharpWintabWintabHwthook(void *param0, int param1, void *param2, void *param3, void *funcPtr)
        {
            throw null;
        }

        public static unsafe System.IntPtr CalliStdCallFuncSystemIntPtr(void *param0, int param1, System.UIntPtr param2, void *param3, void *funcPtr)
        {
            throw null;
        }
    }
}