#include <Windows.h>
#include "DLL.h"

#define NOWTCALLBACKS
#define NOWTFUNCTIONS
#include "WINTAB.H"
#define PACKETDATA 0xFFFF
#define PACKETMODE 0xFFFF
#define PACKETEXPKEYS PKEXT_ABSOLUTE
#define PACKETTOUCHSTRIP PKEXT_ABSOLUTE
#define PACKETTOUCHRING PKEXT_ABSOLUTE
#include "PKTDEF.H"

typedef BOOL(WINAPI* WTENUMPROC)(HCTX, LPARAM); /* changed CALLBACK->WINAPI, 1.1 */
typedef BOOL(WINAPI* WTCONFIGPROC)(HCTX, HWND);
typedef LRESULT(WINAPI* WTHOOKPROC)(int, WPARAM, LPARAM);
typedef WTHOOKPROC FAR* LPWTHOOKPROC;

BOOL API _WTClose(HCTX);
BOOL API _WTConfig(HCTX, HWND);
BOOL API _WTEnable(HCTX, BOOL);
BOOL API _WTExtGet(HCTX, UINT, LPVOID);
BOOL API _WTExtSet(HCTX, UINT, LPVOID);
BOOL API _WTGet(HCTX, LPLOGCONTEXT);
BOOL API _WTGetA(HCTX, LPLOGCONTEXTA);
BOOL API _WTGetW(HCTX, LPLOGCONTEXTW);
BOOL API _WTMgrClose(HMGR);
BOOL API _WTMgrConfigReplace(HMGR, BOOL, WTCONFIGPROC);
BOOL API _WTMgrConfigReplaceEx(HMGR, BOOL, LPSTR, LPSTR);
BOOL API _WTMgrConfigReplaceExA(HMGR, BOOL, LPSTR, LPSTR);
BOOL API _WTMgrConfigReplaceExW(HMGR, BOOL, LPWSTR, LPSTR);
BOOL API _WTMgrContextEnum(HMGR, WTENUMPROC, LPARAM);
BOOL API _WTMgrCsrButtonMap(HMGR, UINT, LPBYTE, LPBYTE);
BOOL API _WTMgrCsrEnable(HMGR, UINT, BOOL);
BOOL API _WTMgrCsrExt(HMGR, UINT, UINT, LPVOID);
BOOL API _WTMgrCsrPressureBtnMarks(HMGR, UINT, DWORD, DWORD);
BOOL API _WTMgrCsrPressureBtnMarksEx(HMGR, UINT, UINT FAR*, UINT FAR*);
BOOL API _WTMgrCsrPressureResponse(HMGR, UINT, UINT FAR*, UINT FAR*);
BOOL API _WTMgrExt(HMGR, UINT, LPVOID);
BOOL API _WTMgrPacketUnhook(HWTHOOK);
BOOL API _WTOverlap(HCTX, BOOL);
BOOL API _WTPacket(HCTX, UINT, LPVOID);
BOOL API _WTQueuePacketsEx(HCTX, UINT FAR*, UINT FAR*);
BOOL API _WTQueueSizeSet(HCTX, int);
BOOL API _WTSave(HCTX, LPVOID);
BOOL API _WTSet(HCTX, LPLOGCONTEXT);
BOOL API _WTSetA(HCTX, LPLOGCONTEXTA);
BOOL API _WTSetW(HCTX, LPLOGCONTEXTW);
DWORD API _WTQueuePackets(HCTX);
HCTX API _WTMgrDefContext(HMGR, BOOL);
HCTX API _WTMgrDefContextEx(HMGR, UINT, BOOL); /* 1.1 */
HCTX API _WTOpen(HWND, LPLOGCONTEXT, BOOL);
HCTX API _WTOpenA(HWND, LPLOGCONTEXTA, BOOL);
HCTX API _WTOpenW(HWND, LPLOGCONTEXTW, BOOL);
HCTX API _WTRestore(HWND, LPVOID, BOOL);
HMGR API _WTMgrOpen(HWND, UINT);
HWND API _WTMgrContextOwner(HMGR, HCTX);
HWTHOOK API _WTMgrPacketHookEx(HMGR, int, LPSTR, LPSTR);
HWTHOOK API _WTMgrPacketHookExA(HMGR, int, LPSTR, LPSTR);
HWTHOOK API _WTMgrPacketHookExW(HMGR, int, LPWSTR, LPSTR);
int API _WTDataGet(HCTX, UINT, UINT, int, LPVOID, LPINT);
int API _WTDataPeek(HCTX, UINT, UINT, int, LPVOID, LPINT);
int API _WTPacketsGet(HCTX, int, LPVOID);
int API _WTPacketsPeek(HCTX, int, LPVOID);
int API _WTQueueSizeGet(HCTX);
LRESULT API _WTMgrPacketHookDefProc(int, WPARAM, LPARAM, LPWTHOOKPROC);
LRESULT API _WTMgrPacketHookNext(HWTHOOK, int, WPARAM, LPARAM);
UINT API _WTInfo(UINT, UINT, LPVOID);
UINT API _WTInfoA(UINT, UINT, LPVOID);
UINT API _WTInfoW(UINT, UINT, LPVOID);
UINT API _WTMgrDeviceConfig(HMGR, UINT, HWND);
WTHOOKPROC API _WTMgrPacketHook(HMGR, BOOL, int, WTHOOKPROC);

static_assert(sizeof(EXTPROPERTY) == 16, "sizeof(EXTPROPERTY)");

auto Wintab32 = DLL(L"Wintab32.dll");

#define GETPROCADDRESS(X) decltype(_##X)* X = Wintab32[#X];

GETPROCADDRESS(WTInfoA)
GETPROCADDRESS(WTInfoW)
GETPROCADDRESS(WTOpenA)
GETPROCADDRESS(WTOpenW)
GETPROCADDRESS(WTPacketsGet)
GETPROCADDRESS(WTClose)
GETPROCADDRESS(WTPacket)
GETPROCADDRESS(WTEnable)
GETPROCADDRESS(WTOverlap)
GETPROCADDRESS(WTConfig)
GETPROCADDRESS(WTGetA)
GETPROCADDRESS(WTGetW)
GETPROCADDRESS(WTSetA)
GETPROCADDRESS(WTSetW)
GETPROCADDRESS(WTExtGet)
GETPROCADDRESS(WTExtSet)
GETPROCADDRESS(WTSave)
GETPROCADDRESS(WTRestore)
GETPROCADDRESS(WTPacketsPeek)
GETPROCADDRESS(WTDataGet)
GETPROCADDRESS(WTDataPeek)
GETPROCADDRESS(WTQueueSizeGet)
GETPROCADDRESS(WTQueueSizeSet)
GETPROCADDRESS(WTMgrOpen)
GETPROCADDRESS(WTMgrClose)
GETPROCADDRESS(WTMgrContextEnum)
GETPROCADDRESS(WTMgrContextOwner)
GETPROCADDRESS(WTMgrDefContext)
GETPROCADDRESS(WTMgrDefContextEx)
GETPROCADDRESS(WTMgrDeviceConfig)
GETPROCADDRESS(WTMgrConfigReplace)
GETPROCADDRESS(WTMgrPacketHook)
GETPROCADDRESS(WTMgrPacketHookDefProc)
GETPROCADDRESS(WTMgrExt)
GETPROCADDRESS(WTMgrCsrEnable)
GETPROCADDRESS(WTMgrCsrButtonMap)
GETPROCADDRESS(WTMgrCsrPressureBtnMarks)
GETPROCADDRESS(WTMgrCsrPressureResponse)
GETPROCADDRESS(WTMgrCsrExt)
GETPROCADDRESS(WTQueuePacketsEx)
GETPROCADDRESS(WTMgrConfigReplaceExA)
GETPROCADDRESS(WTMgrConfigReplaceExW)
GETPROCADDRESS(WTMgrConfigReplaceEx)
GETPROCADDRESS(WTMgrPacketHookExA)
GETPROCADDRESS(WTMgrPacketHookExW)
GETPROCADDRESS(WTMgrPacketHookEx)
GETPROCADDRESS(WTMgrPacketUnhook)
GETPROCADDRESS(WTMgrPacketHookNext)
GETPROCADDRESS(WTMgrCsrPressureBtnMarksEx)
